-- SLTR_LC_BAN_WORD_DEF
CREATE TABLE SLTR_LC_BAN_WORD_DEF(
	OBJ_ID TEXT PRIMARY KEY,
	USER_OBJ_ID TEXT NOT NULL,
	BAN_WORD TEXT NOT NULL,
	LANG_CD TEXT,
	WORD_CATE_CD TEXT NOT NULL,
	ALTER_WORD TEXT,
	USE_YN TEXT NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER_ID TEXT,
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_USER_ID TEXT,
	UNIQUE(BAN_WORD)
);

-- SLTR_LC_USER_DEF
CREATE TABLE SLTR_LC_USER_DEF(
	OBJ_ID	TEXT PRIMARY KEY,
	USER_ID	TEXT NOT NULL,
	USER_NAME	TEXT NOT NULL,
	ACTV_LIC_ID	TEXT,
	ACTV_DATE	TIMESTAMP,
	USD_EXCH_RATE	NUMBER,
	CNY_EXCH_RATE	NUMBER,
	BASE_MGN_RATE	NUMBER,
	BASE_MGN_VALUE	NUMBER,
	CUSTM_EXCD_MGN_RATE	NUMBER,
	CUSTM_EXCD_MGN_VALUE	NUMBER,
	SHIP_FEE_TYPE	TEXT,
	BASE_SHIP_FEE	NUMBER,
	RTRN_SHIP_FEE	NUMBER,
	EXCD_SHIP_FEE	NUMBER,
	MFR_NAME	TEXT,
	BRAND_NAME	TEXT,
	UNDR_PUR_AVAIL_FLAG	TEXT,
	THUMB_OPTION_YNl TEXT,
	HASH_TAG_AUTO_YN	TEXT DEFAULT 'Y',
	TOP_IMG_USE_FLAG	TEXT,
	BASE_TOP_IMG_USE_FLAG	TEXT,
	BOT_IMG_USE_FLAG	TEXT,
	BASE_BOT_IMG_USE_FLAG	TEXT,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER_ID	TEXT,
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_USER_ID	TEXT,
	UNIQUE(USER_ID)
);

-- SLTR_LC_IMG_DTL
CREATE TABLE SLTR_LC_IMG_DTL(
	OBJ_ID	TEXT PRIMARY KEY,
	USER_ID	TEXT NOT NULL,
	IMG_TYPE	TEXT NOT NULL,
	IMG_FILE_PATH	TEXT,
	IMG_SEQ	TEXT NOT NULL,
	IMG_FILE_NAME	TEXT,
	IMG_FILE_SIZE	NUMBER,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER_ID	TEXT,
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_USER_ID	TEXT,
	UNIQUE(USER_ID, IMG_SEQ, IMG_FILE_NAME)
);


-- SLTR_LC_BIZ_DEF
CREATE TABLE SLTR_LC_BIZ_DEF(
	OBJ_ID	TEXT PRIMARY KEY,
	USER_ID	TEXT NOT NULL,
	BIZ_REG_NUM	TEXT NOT NULL,
	BIZ_NAME	TEXT NOT NULL,
	REP_USE_NAME	TEXT NOT NULL,
	BIZ_ADDR	TEXT NOT NULL,
	BIZ_START_DATE	TIMESTAMP NOT NULL,
	DISP_SEQ	NUMBER NOT NULL,
	USE_YN	TEXT,
	LAST_VALID_DATE	TIMESTAMP,
	BASE_MGN_RATE	NUMBER,
	BASE_MGN_VALUE	NUMBER,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER_ID	TEXT,
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_USER_ID	TEXT,
	UNIQUE(USER_ID, BIZ_REG_NUM)
);

-- SLTR_LC_BIZ_MKT_REL
CREATE TABLE STLR_LC_BIZ_MKT_REL(
	OBJ_ID	TEXT PRIMARY KEY,
	USER_OBJ_ID	TEXT NOT NULL,
	BIZ_OBJ_ID	TEXT NOT NULL,
	MKT_ID	TEXT NOT NULL,
	MKT_USER_ID	TEXT NOT NULL,
	MKT_USER_PWD	TEXT,
	API_ACCESS_KEY	TEXT,
	API_SECRET_KEY	TEXT,
	MKT_COMPANY_CODE	TEXT,
	AUTO_CONNECT_YN	TEXT DEFAULT 'Y' ,
	AUTO_PROD_UPLOAD_YN	TEXT DEFAULT 'N',
	MGN_RATE	NUMBER DEFAULT 50,
	MGN_BASIC	NUMBER DEFAULT 5000,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER_ID	TEXT,
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_USER_ID	TEXT,
	UNIQUE(USER_OBJ_ID, BIZ_OBJ_ID, MKT_ID)

);

-- SLTR_LC_MKT_DEF
CREATE TABLE SLTR_LC_MKT_DEF(
	OBJ_ID	TEXT PRIMARY KEY,
	MKT_ID	TEXT NOT NULL,
	MKT_NAME TEXT NOT NULL,
	MKT_TYP	TEXT NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER_ID	TEXT,
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_USER_ID	TEXT,
	UNIQUE(MKT_ID)
);


-- SLTR_LC_KEYWORD
CREATE TABLE SLTR_LC_KEYWORD(
	OBJ_ID	TEXT PRIMARY KEY,
	USER_OBJ_ID	TEXT NOT NULL,
	PROD_KEYWORD	TEXT NOT NULL,
	SRC_MKT_ID	TEXT NOT NULL,
	KEYWORD_URL	TEXT,
	SEARCH_KEYWORD	TEXT,
	SUBJECT_KEYWORD	TEXT,
	SUBJECT_LOC_TYPE	TEXT,
	HASH_TAG	TEXT,
	AUTO_SEARCH_YN	TEXT,
	COLLECT_START_PAGE	NUMBER,
	COLLECT_END_PAGE	NUMBER,
	BASE_MGN_RATE	NUMBER,
	BASE_MGN_VALUE	NUMBER,
	REGIST_DATE	TIMESTAMP,
	COLLECT_PROD_YN	TEXT,
	LAST_COLLECT_DATE	TIMESTAMP,
	PROD_QTY	NUMBER,
	COLLECT_QTY	TEXT,
	CP_CATEGORY	TEXT,
	SS_CATEGORY	TEXT,
	E11ST_CATEGORY	TEXT,
	GM_CATEGORY	TEXT,
	INTPK_CATEGORY	TEXT,
	FAV_KEYWARD_YN TEXT,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER_ID	TEXT,
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_USER_ID	TEXT,
	UNIQUE(USER_OBJ_ID, PROD_KEYWORD, SRC_MKT_ID)
);

-- SLTR_LC_PROD_REGIST
CREATE TABLE SLTR_LC_PROD_REGIST(
	OBJ_ID	TEXT PRIMARY KEY,
	USER_OBJ_ID	TEXT NOT NULL,
	REG_PROD_ID	TEXT NOT NULL,
	COLLECT_PROD_OBJ_ID	TEXT NOT NULL,
	TRGT_MKT_ID	TEXT NOT NULL,
	REG_VERSION	NUMBER,
	REG_PRICE	 NUMBER,
	PRICE_CURRENCY	TEXT,
	TRGT_PROD_URL	TEXT,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER_ID	TEXT,
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_USER_ID	TEXT,
	UNIQUE(USER_OBJ_ID, REG_PROD_ID)
);


-- SLTR_LC_CODE_DEF
CREATE TABLE SLTR_LC_CODE_DEF(
	OBJ_ID	TEXT PRIMARY KEY,
	CODE_CLASS_ID	TEXT NOT NULL,
	CODE_ID	TEXT NOT NULL,
	KOR_CODE_NAME	TEXT,
	ENG_CODE_NAME	TEXT,
	USE_YN	TEXT,
	DESCRIPT	TEXT,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CREATE_USER_ID	TEXT,
	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATE_USER_ID	TEXT,
	UNIQUE(CODE_CLASS_ID, CODE_ID)
)
