package com.tsh.slt.sua.domain.util;

import java.util.ArrayList;
import java.util.Arrays;

public class WordMassaging {

    public static ArrayList<String> getBanWordList() {
        ArrayList<String> arrayList = new ArrayList<>(Arrays.asList("ADER",
                "ADERERROR",
                "A Glas Tr",
                "ADIDAS",
                "ALLSAINTS",
                "AMIRO",
                "ANEW ",
                "BT21 ",
                "BTS ",
                "Benzylsildenafil",
                "Berberine",
                "Belladonna",
                "Bergenin",
                "Black Cohosh",
                "Brahmi",
                "Buchu leaf",
                "Agathosma betulina",
                "Buckthorn",
                "Bull's foot",
                "Butea gum tree",
                "Butea superba",
                "Buthus martensii Karsch",
                "Butterfly Pea",
                "C-REST",
                "C-레스트",
                "CDG",
                "CELINE",
                "Caesalpinia Benthamiana",
                "Cannabis sativa L",
                "Carbodenafil",
                "Cartoon Korea",
                "Cascara sagrada",
                "Cascaroside",
                "Cassia occidentalis",
                "Cat's Claw",
                "Catuaba",
                "Cha De bugre",
                "ChineseClubmoss",
                "Chlorodenafil",
                "Chloropretadalafil",
                "Chlorosibutramine",
                "Chlorosipentramine",
                "Chromium Argninate",
                "Chromium Picolinate",
                "Cimicifuga recomosa",
                "Cinnamyldenafil",
                "Cis-cyclopentyltadalafi",
                "Citicoline",
                "Citrulline Malate",
                "Clubmoss",
                "Clubmoss Extract",
                "Colt's foot",
                "Coltsfoot",
                "Cordia Salicifolia",
                "Couch Grass",
                "Coughwort",
                "Crataegus mexicana",
                "Creeping butea",
                "Cyanotis Vaga",
                "Cyclopentynafil",
                "Cysteine",
                "D-chlorpheniramine",
                "DAIWA",
                "DEPROJECT",
                "DMAA",
                "DMBA",
                "DSQ2",
                "Dawa",
                "Dehydroepiandrosterone",
                "Demethylhongdenafil",
                "Demethyltadalafil",
                "Descarbonsildenafil",
                "Desmethylsibutramine",
                "Desulfovardenafil",
                "Devil's Claw Root",
                "Dexamethasone",
                "Diawa",
                "Dichlorodenafil",
                "Didesmethylsibutramine",
                "Diindolylmethane",
                "Dimethylsildenafil",
                "Dimethylthiosildenafil",
                "Dinitrophenol",
                "Dinotaeng",
                "Diosmin",
                "Dithiopropylcarbodenafil",
                "Diwa",
                "Dolmite",
                "E131 Patent blue V",
                "ERMENE",
                "ESSENTIALS",
                "Echinacea spp",
                "Elymus repens",
                "Ephedrine",
                "Epimedium Grandiflorum",
                "Epimedium sagittatum",
                "Epinephrine",
                "Erotic",
                "Eurycoma Longifolia",
                "Eviscer",
                "Farfara",
                "Farfarae flos",
                "Fenfluramine",
                "Fieldhove",
                "Fluoxetine",
                "Foal's wort",
                "Forsythia suspensa extract",
                "Fucoxanthin",
                "Furosemide",
                "GABA ",
                "GARCONS",
                "GHB ",
                "GOYARD",
                "GTD ",
                "Gamma-aminobutyric acid",
                "Garcinia Quaesita",
                "Gelsemium Sempervirens",
                "Gendenafil",
                "Geographic ",
                "Glibenclamide",
                "Gliclazide",
                "Glimepiride",
                "Glipizide",
                "Goldenseal Root",
                "Gravel Root",
                "Griffonia simplicifolia seed extract",
                "Guggul Extract",
                "Gymnema Sylvestre",
                "HENTAI",
                " HOTO",
                "Hardcore",
                "Harpagophytum procumbens",
                "Have eyes",
                "Hemp ",
                "Histamine",
                "Histamine HCl",
                "Histamine Hydrochloride",
                "Homosildenafil",
                "Hongdenafil",
                "Hoodia Cactus powder",
                "Hoodia Gordonii",
                "Horny goat weed",
                "Horse Chestnut ",
                "Horse hoof",
                "Horse-foot",
                "Horse-shoe",
                "Horsehoof",
                "Hydroxychlorodenafil",
                "Hydroxyhomosildenafil",
                "Hydroxyhongdenafil",
                "Hydroxythiohomosildenafil",
                "Hydroxyvardenafil",
                "Icariin",
                "Imidazosagtriazinone",
                "Indian Snake Root",
                "Isopropylnortadalafil",
                "JBL ",
                "JSEX",
                "Jacob",
                "Jacquemus",
                "Johnson’s Baby",
                "KAMAGRA",
                "KDsafe",
                "Kava kava",
                "Kavain",
                "L-Cysteine",
                "L-Selenomethionine",
                "L-citrulline",
                "L-dopa",
                "L-ornithine",
                "L-오르니틴",
                "LET'SSLIM",
                "LeagueofLegends",
                "Levothyroxine",
                "Ligustrum Berry",
                "Linachouchou ",
                "Line Friends",
                "Liothyronine",
                "Lipoic acid",
                "Lobelia",
                "Lobster",
                "Longa",
                "Longjack",
                "Lumbrokinase",
                "MARK&LONA",
                "MCM ",
                "Microcystin",
                "Mirodenafil",
                "Missoni",
                "Montanoa",
                "Montanoa Tomentosa",
                "Mucuna Pruriens seed",
                "Muira Puama",
                "N2O ",
                "NSR ",
                "Naked",
                "National Geographic",
                "Nitrodenafil",
                "Norneosildenafil",
                "Norneovardenafil",
                "Nude",
                "OX-EYE DAISY",
                "Orlistat",
                "Orthosiphon stamineus",
                "Oxilofrine",
                "Oxohongdenafil",
                "PABA",
                "PAMU",
                "PONY",
                "PRADA",
                "PUBG",
                "PXG",
                "Papaver somniferum",
                "Para-aminobenzoic acid",
                "PavonetKlotzsch",
                "Phellodendri Cortex",
                "Phellodendron",
                "Phellodendron amurense Ruprecht",
                "Phellodendron bark",
                "Phellodendron chinense Schneider",
                "Phenolphthalein",
                "Phenylethylamine",
                "Phyllanthus amarus",
                "Pinellia Tuber",
                "Pinellia ternata Breitenbach",
                "Piperidinohongdenafil",
                "Polene",
                "Pomegranate Seed",
                "Pomegranate bark",
                "Porno",
                "Prickly Chaff",
                "Propoxyphenyl-thioaildenafil",
                "Propoxyphenylthiohomosildenafil",
                "Propoxyphenylthiohydroxyhomosildenafil",
                "Propoxyphenylthiosildenafil",
                "Pseudovardenafil",
                "Ptychopetalum olacoides",
                "Pueraria mirifica",
                "Pygeum Africanum",
                "R-Lipoic acid",
                "RIMOWA",
                "Radix morindae officinalis",
                "Raspberry Ketone",
                "Rauwolfia serpentina",
                "Red root bark",
                "Redkwaokrua",
                "Rhamnus frangula",
                "Rhaponticum Carthamoides",
                "Rheum officinale Bailon",
                "Rheum palmatum",
                "Rheum tanguticum",
                "Rhodea japonica Roth",
                "Rhubarb",
                "Rydenacw",
                "SaengQ",
                "Salacia",
                "Salix Alba",
                "Scorpion",
                "Secret cam",
                "Seman Pruni",
                "Senna",
                "Sennoside",
                "Sexes",
                "Shilajit",
                "Sibutramine",
                "Sildenafil",
                "Slippery Elm",
                "Synephrine",
                "TBTHOM",
                "TB브랜드",
                "THOMBROWNE",
                "Tadalafil",
                "Tejocote root",
                "Terminalia arjuna",
                "Thiohomosildenafil",
                "Thioquinapiperifil",
                "Thiosildenafil",
                "Tongkat Ali",
                "Totoro",
                "Trans-cyclopentyltadalafil",
                "Trichopus Zeylanicus",
                "Tussilago farfara Linné",
                "Udenafil",
                "Uglybros",
                "Ulmus rubra",
                "Uncaria Tomentosa",
                "VETEMENTS",
                "Vardenafil",
                "Veratri Rhizoma et Radix",
                "Veratrum",
                "Verbanalin",
                "Verbena",
                "Vervain",
                "Vinca minor",
                "Vinpocetine",
                "Vipoint",
                "Vitamin K2",
                "White Hellebore",
                "White willow",
                "Wiggle",
                "Wild Yam",
                "Xanthoanthrafil",
                "Yohimbin",
                "Youpin",
                "ZARA ",
                "Zinc citrate",
                "aegismax",
                "ahegao",
                "applique ",
                "aquapick",
                "bang duck",
                "bbang bbang duck",
                "bbang duck",
                "bewell",
                "bigbang",
                "bigbang golf",
                "black snake root",
                "bovine",
                "brassard",
                "brunch brother",
                "brunchbrother",
                "cam mini",
                "chanel",
                "chicab",
                "cichona bark",
                "cis-사이클로펜틸타다라필",
                "clock fan",
                "cognizen",
                "condom",
                "constantinpanerai",
                "coutur",
                "crocs ",
                "desmethylcarbodenafil",
                "dhea ",
                "dinitrophenyl",
                "drpk ",
                "dynafit",
                "eobubaga",
                "eobubagabang",
                "fan clock",
                "fetish",
                "gamakatsu",
                "geographic",
                "germanium",
                "givenchy",
                "glas tr",
                "gorilla glass",
                "gucci",
                "guggul",
                "guggulsterones",
                "hewolf",
                "hidden TF",
                "hidden cam",
                "hidden camera",
                "home security",
                "homotadalafil",
                "j.estina",
                "jammer",
                "jammer Shield",
                "jpx ",
                "juicycoutur",
                "kaempferia parviflora",
                "kakao",
                "kakao friends",
                "kawa kawa",
                "lacoste",
                "led clock face",
                "led clock fan",
                "led fan",
                "lesser periwinkle",
                "lindy ",
                "livis ",
                "maacarons handy fan",
                "magnolia officinalis",
                "majorgolf",
                "mandelda",
                "markandlona",
                "maxmara",
                "melatonin",
                "message fanusb",
                "myopia",
                " national ",
                "noritake",
                "northface",
                "penis ",
                "quinna tree bark",
                "resin ",
                "scorpio",
                "screen protector",
                "seago",
                "secret audio",
                "secret camera",
                "security cam",
                "security camera",
                "sexual",
                "sg987",
                "slingshot",
                "spanishfly",
                "starbucks",
                "stealth",
                "stigma",
                "stone island",
                "stoneisland",
                "techage",
                "thermometro",
                "tiltlelst",
                "titleist",
                "tommy ",
                "trans-사이클로펜틸타다라필",
                "tws ",
                "uav 방패",
                "ufo가습기",
                "underarmour",
                "usb led clock",
                "wiretapping",
                "yohimbe",
                " benepom",
                "​TAW&TOW",
                "​라코스테",
                "가마가츠",
                " 가스 ",
                "가재",
                "간첩",
                "감청",
                "강간",
                "개밀",
                "게르마늄",
                "겐데나필",
                "겔세민",
                "고야드",
                "곤약",
                "골든씰 뿌리",
                "과수원젤",
                "관장",
                "구레모나체",
                "구찌",
                "귀두",
                "귀축미학",
                "근골초",
                "근시",
                "글루코만난",
                "글리메피리드",
                "글리벤클라미드",
                "글리클라짓",
                "글리피짓",
                "까르띠에",
                "꼬마젤",
                "꼬추",
                "꼭두서니과",
                "꼼데가르송",
                "나가니시",
                "나이키",
                "난시",
                "남근",
                "남성확대",
                "내셔너",
                "내셔널 지오그래픽",
                "내셔널지오그래픽",
                "네이처하이크",
                "네이쳐하이크",
                "네츄럴핫젤",
                "넥밴드선풍기",
                "넥스가드 스펙트라",
                "넥스가드스펙트라",
                "노르네오바데나필",
                "노르네오실데나필",
                "노리타케",
                "노스페이스",
                "노예",
                "누드 ",
                "뉴트리코어",
                "느릅나무",
                "니트로데나필",
                "다이노탱",
                "다이와",
                "당살초",
                "대원미디어",
                "데메칠타다라필",
                "데메틸홍데나필",
                "데설포바데나필",
                "데스메틸시부트라민",
                "데스메틸카보데나필",
                "데스카본실데나필",
                "덱사메타손",
                "도넛가습기",
                "도수 ",
                "도인",
                "도청",
                "도촬",
                "돌로마이트",
                "돌체구스토",
                "두카티",
                "드라코",
                "드론 방해 기",
                "디니트로페놀",
                "디데스메틸시부트라민",
                "디메칠실데나필",
                "디메틸치오실데나필",
                "디즈니",
                "디치오프로필카보데나필",
                "디클로로데나필",
                "디프로젝터",
                "디프로젝트",
                "딜도",
                "딸딸이",
                "라이언",
                "라이엇게임즈",
                "라즈베리케톤",
                "라코스테",
                "랄프로렌",
                "러브링",
                "러브젤",
                "레보치록신",
                "레이스 링",
                "레즈비언",
                "레코더",
                "렛츠슬림",
                "로리타",
                "로스젤",
                "롱타임젤",
                "루돌프가습기",
                "루이비똥",
                "루이비통",
                "룸브로키나제",
                "리그오브레전드",
                "리락쿠마",
                "리모와",
                "리바이스",
                "리얼음순",
                "리오치로닌",
                "리포산",
                "린드버그",
                "마스터베이션",
                "마약",
                "마이크로 광진",
                "마이크로시스틴",
                "마카롱 선풍기",
                "마카롱휴대용선풍기",
                "마크앤로나",
                "마편초",
                "막스마라",
                "만년청",
                "만델다",
                "메세지 선풍기",
                "메세지선풍기",
                "메시지 팬",
                "메시지선풍기",
                "메이저골프",
                "메종드사브레",
                "메틸코발아민",
                "메틸하이드록시호모실데나필",
                "멜라토닌",
                "명민주",
                "모로",
                "모피 ",
                "몰래 ",
                "몰래카메라",
                "몰약",
                "몰카",
                "미니 멜리사",
                "미로데나필",
                "미소시스틴",
                "미쏘니",
                "미즈노",
                "미키",
                "바데나필",
                "바디캠",
                "바이브레이터",
                "반대로 간첩",
                "반하",
                "방탄 소년단",
                "방탄소년단",
                "방해 기",
                "방해 전파 카메라",
                "배틀그라운드",
                "백운석",
                "백하초",
                "버바인",
                "벅턴",
                "벌거 벗은",
                "벗은 여자",
                "베르베린",
                "벤자민무어",
                "벤질실데나필",
                "벨라돈나",
                "보g",
                "보모",
                "보안 카메라",
                " 보지 ",
                "부랄",
                "불독 ",
                "불독방향제",
                "불알",
                "브라더형제",
                "브런치식빵케이스",
                "블랙 코호시",
                "비스트 모드",
                "비웰",
                "빅뱅",
                "빅뱅골프",
                "빈포세틴",
                "빵덕이",
                "빵빵덕",
                "사라시아",
                "사정지연",
                "산리오",
                "살모사",
                "살인",
                "살충제",
                "새총",
                "색녀",
                " 색스",
                "색쓰",
                "생리",
                "생큐",
                "생프로바이오틱스",
                "샤넬",
                "샤넬폰케이스",
                "샤키볼링바이브레이터",
                "샤프나체",
                "석궁",
                "석류씨",
                "석송",
                "성감대",
                "성교",
                " 성기 ",
                "성기능부전개선",
                "성생활",
                "성인게임",
                "성인비디오",
                "세신 ",
                "세신드릴",
                "세정기",
                "섹도구",
                " 섹스 ",
                "섹쑤",
                "섹쓰",
                "센나",
                "센노사이드",
                "셀린느",
                "셀린드",
                "셍큐",
                "소년단",
                "수면제",
                "수면제 ",
                "슈도바데나필",
                "스킨레스",
                "스타벅스",
                "스텔스",
                "스톤 아일랜드",
                "스톤아일랜드",
                "스티그마",
                "슬링샷",
                "시계 선풍기",
                "시력",
                "시마노",
                "시부트라민",
                "시스테인",
                "식빵케이스",
                "식용 ",
                "식용잉크",
                "신나밀데나필",
                "신비아파트",
                "신호 탐지기",
                "신호탐지기",
                "실데나필",
                "싸이클로펜티나필",
                "쌕스",
                "쎅스",
                "씨디지",
                "아디다스",
                "아르뉴",
                "아미노타다라필",
                "아미로",
                "아바나필",
                "아산화질소",
                "아세트아미노타다라필",
                "아세틸바데나필",
                "아세틸산",
                "아스트로글라이드",
                "아오엠크",
                "아쿠아픽",
                "아헤가오",
                "안전띠",
                "안전클립",
                "안티 스파이",
                "안티 위치",
                "알몸",
                "암모늄",
                "애널",
                "애로",
                "애무",
                "야한",
                "어뉴",
                "어부바",
                "어부바가방",
                "어안 렌즈",
                "어피치",
                "언더아머",
                "에널",
                "에로 ",
                "에로구",
                "에르메네",
                "에르메스",
                "에키네시아 속",
                "에페드린",
                "연교",
                "연꽃정수기",
                "열등용사의",
                "영양제 ",
                "영이의숲",
                "오나홀",
                "오랄",
                "오럴",
                "오르가슴",
                "오르가즘",
                "오르리스타트",
                "오리지날핫젤",
                "오션 팩",
                "오션팩",
                "오줌",
                "오징어 게임",
                "오징어게임",
                "오카모토",
                "옥소홍데나필",
                "옥틸노르타다라필",
                "체온계 ",
                "올세인츠",
                "와이드 뷰 ",
                "외음부",
                "요핀",
                "요힘베",
                "요힘빈",
                "우유 음료",
                "욱일기",
                "위즈굿",
                "유근피",
                "유데나필",
                "유도제",
                " 유방 ",
                "유연한 시간",
                "음경",
                "음란",
                "음모",
                "음부",
                "의료 ",
                "의료게르마늄",
                "이미다조사가트리아지논",
                "이산화질소",
                "이소프로필노르타다라필",
                "이카린",
                "인도사목",
                "인민공화국",
                "입생로랑",
                " 자극기 ",
                "자위",
                " 자지 ",
                "잔소안트라필",
                "정력",
                "젖꼭지",
                "젖탱이",
                "제스트라",
                "제이비엘",
                "제이지 ",
                "제이지컴퍼니",
                "젠틀몬스터",
                "조개나물",
                "조루방지",
                "조임",
                " 주사 ",
                "줄줄이애널",
                "쥬니꾸뛰르",
                "지방시",
                "지상부",
                "지스팟",
                "지오그래픽",
                "진동바이브레이터",
                "진주기구",
                "질흥분제",
                "차이 핏",
                "참억새성기헤이",
                "창녀",
                "체온계",
                "체위",
                "초소형 캠",
                "초소형 홈",
                "최음",
                "최음제",
                "치오실데나필",
                "치오퀴나피페리필",
                "치오호모실데나필",
                "카보데나필",
                "카스카라사그라다",
                "카스카로사이드",
                "카카오",
                "카카오프렌즈",
                "칸나체",
                "캐롤라이나 쟈스민",
                "캘빈클라인",
                "케이트스페이드",
                "케이팝",
                "콘돔",
                "쿤닐링",
                "크록스",
                "클로로데나필",
                "클로로시부트라민",
                "클로로시펜트라민",
                "클로로페니라민",
                "클로로프레타다라필",
                "키나나무",
                "타다라필",
                "타미힐피거",
                "타이들리스트",
                "타이틀리스트",
                "타일러리스트",
                "토토로",
                "톰브라운",
                "톰브랜드",
                "톰패션",
                "투시경",
                "파노라마",
                "파워진동먹쇠",
                "판더코리아",
                "판도라 ",
                "패니스",
                "패션TB",
                "패티쉬",
                "페놀프탈레인",
                "페니스",
                "페어라이어",
                "페이퍼랑",
                "페티쉬",
                "페티시",
                "페페로션",
                "펜플루라민",
                "펠라치오",
                "포르노",
                "포르노걸",
                "포켓샷",
                "폰섹",
                "폴렌",
                "폴렌느",
                "폴로 랄프",
                "푸로세미드",
                "퓨마",
                "프라다",
                "프로폭시페닐치오실데나필",
                "프로폭시페닐치오아일데나필",
                "프로폭시페닐치오호모실데나필",
                "플레이나체",
                "플레이보이핫젤",
                "플루옥세틴",
                "피콜린산 크롬",
                "피페리디노홍데나필",
                "핀홀",
                "하이드록시바데나필",
                "하이드록시치오호모실데나필",
                "하이드록시클로로데나필",
                "하이드록시호모실데나필",
                "하이드록시홍데나필",
                "한류",
                "할리데이비슨",
                "핫핑거",
                "항문",
                "핸타이",
                "헨타이",
                "혈압계",
                "호모실데나필",
                "호모타다라필",
                "홀스캐슈너츠",
                "홈 보안",
                "홍데나필",
                "확대크림",
                "후박",
                "흑생강",
                "흥분젤",
                "흰버드나무",
                "히로뽕",
                "안전 클립",
                "안전벨트",
                "안전 벨트",
                "벨트클립",
                "벨트 클립",
                "EENK",
                "ThomBrowne",
                "AXESEA",
                "RIPNDIP",
                "NERDY",
                "샤넬",
                "Chanel",
                "DIOR",
                "uptownholic",
                "ODDONEOUT",
                "MoMA",
                "나이키",
                "NIKE",
                " noah ",
                "monton",
                "REKKEN",
                "MOFT ",
                "OTZ ",
                "Korin ",
                "TOI ",
                "Equipment ",
                "TWILLY ",
                "HUMTTO ",
                "Crocs ",
                "크록스 ",
                "polene ",
                "AudemarsPiguet ",
                "depound ",
                "RRL ",
                "ROLAROLA ",
                "LAFESTIN ",
                "라페스틴",
                "PETKIT ",
                "펫킷",
                "Flynova ",
                "플라이노바",
                "캘빈클라인",
                "givenchy",
                "지방시",
                "레트슬림",
                "제트슬림",
                "aquapick",
                "아쿠아픽",
                "zzlddong",
                "즐똥",
                "타이들리스트",
                "kellybag ",
                "켈리백",
                "넥밴드선풍기",
                "돌체엔",
                "D&G",
                "노스페이스",
                "겐조 ",
                "KENZO ",
                "mellow ",
                "northface ",
                "KLASONBEL",
                "맥퀸",
                "McQueen",
                "연꽃정수기",
                "dainese ",
                "다이네즈",
                "lacoste",
                "라코스테",
                "taylormade",
                "테일러메이드",
                "입생로랑",
                "armani",
                "아르마니",
                "ETRO ",
                "에트로",
                "에스까나",
                "ERMENE ",
                "에르메네",
                "alvieromartini",
                "알비에로마르티니",
                "ANNASUI",
                "안나수이",
                "icebug ",
                "아이스버그",
                "aigner",
                "아이그너 ",
                "agatha ",
                "아가타 ",
                "swarovski",
                "스와로브스키",
                "SEIKO  ",
                "세이코 ",
                "Versace ",
                "베르사체",
                "브릭스 ",
                "Burberry",
                "버버리",
                "BALLY ",
                "balenciaga",
                "발렌시아가",
                "MIUMIU",
                "미우미우",
                "Missoni",
                "미쏘니",
                "maxmara",
                "막스마라",
                "montblanc",
                "몽블랑",
                "Jacob ",
                "마크제이콥스",
                "LULU ",
                "루루기네스",
                "chloe ",
                "끌로에",
                "loewe ",
                "로에베",
                "PXG ",
                "Malbon",
                "어린이",
                "보양",
                "버프",
                "3D curve",
                "A wolf",
                "A/V신호수신기",
                "A6OVE",
                "Abloh",
                "acw",
                "AD/DA 변환장치",
                "ADER",
                "adult bb gun",
                "alkali",
                "Alpine use",
                "amplifier",
                "animation",
                "Anti Social",
                "anus",
                "apeach",
                "aphrodisiac",
                "apple",
                "arm band",
                "armband",
                "assistant suit",
                "astigmatism",
                "audio recorder",
                "automatic pressure switch",
                "auxiliary battery",
                "babapapa",
                "Baby",
                "backdrop",
                "Backwards",
                "bad rabbit",
                "ballast",
                "bamboo band",
                "banknote counter",
                "Bao Bao",
                "barbapapa",
                "BASEUS",
                "batman",
                "baton",
                "battery",
                "bb gun",
                "bb teen",
                "beast",
                "beast mode",
                "beastmode",
                "beer case",
                "bench press",
                "berus",
                "bewell",
                "Big Bang",
                "big bust",
                "bigbang",
                "BILLIONAIRE",
                "binding",
                "blind",
                "boat",
                "bodybuilding",
                "Boiler",
                "Bone Champions",
                "booster",
                "Boots",
                "born champs",
                "boy london",
                "brake",
                "brake fluid",
                "Brake for up speed prevention device",
                "breaker",
                "breast",
                "breasted suit",
                "BTOB",
                "BTS",
                "bubble generator",
                "buffer",
                "Built-in ballast LED lamp",
                "built-in lamp",
                "bumper cushion",
                "bumper ring",
                "buoyancy",
                "Burlon",
                "bus stop bus information system",
                "Business Suit",
                "butane",
                "butterfly",
                "cacao",
                "camelback",
                "capacitor",
                "Capacitors for Fluorescent Lamps",
                "Captain",
                "Captain America",
                "car design",
                "carina",
                "cartoon",
                "Cartoon Korea",
                "cash machine",
                "cash register",
                "Cashmere",
                "CATV방송수신기",
                "CCTV",
                "cdg",
                "cell phone battery charger",
                "cellphone",
                "chain type",
                "charger",
                "Chihiro",
                "child",
                "Chopper",
                "circuit breaker for device protection",
                "circuit breaker for wiring",
                "cleaner",
                "clear view",
                "climbing rope",
                "cockle",
                "code",
                "code set",
                "code switch",
                "coin counter",
                "cold",
                "Combustion",
                "Complex terminal device",
                "compressor",
                "compressor gate",
                "connecting parts",
                "Connectors for electrical equipment",
                "constantin",
                "Converter for lighting equipment",
                "cordless power tools",
                "corduroy",
                "Crow",
                "Crown",
                "crown pendant necklace",
                "cutting machine",
                "daiwa",
                "dawa",
                "DC power supply",
                "deer",
                "deer marble",
                "dehydrator",
                "descendants of the sun",
                "design cartoon",
                "digital door lock",
                "dimmer",
                "discharge lamp",
                "disk",
                "Disney",
                "distillation",
                "doctor",
                "donut",
                "door lock",
                "Doraemon",
                "dpark",
                "DPRK",
                "Dr Dre",
                "draco",
                "Dragon Ball",
                "Drinking",
                "drug",
                "ducati",
                "duck",
                "ear pads",
                "earth leakage breaker",
                "edison",
                "edison thread holder",
                "editor",
                "electric bathtub",
                "electric bed",
                "electric bicycle",
                "electric board",
                "electric bread cutter",
                "electric charger",
                "electric clock",
                "electric cushion",
                "Electric drive motor start relay",
                "electric fitness equipment",
                "electric heated bed",
                "electric heater",
                "electric heating board",
                "electric hot water mat",
                "electric hot water pump",
                "electric liquor aging machine",
                "Electric refrigeration and refrigeration equipment",
                "electric stand",
                "electric steamer",
                "electric typewriter",
                "electric washer",
                "electric washing machine",
                "electric water fountain",
                "electric water ionizer",
                "electric water purifier",
                "electric welding machine",
                "electrical device",
                "electrical equipment",
                "electrodeless lamp",
                "electromagnetic brake",
                "electromagnetic switch",
                "Electronic ballast for lamps",
                "electronic blackboard",
                "electronic board",
                "electronic starter",
                "electronic switch",
                "electronic table",
                "electronic watch",
                "Elementary student",
                "Elsa",
                "emergency stop",
                "enema",
                "energy",
                "energy regulator",
                "energy storage",
                "epilator",
                "ESLOE",
                "even a walker",
                "exercise slider",
                "eye protection",
                "Eyelashes",
                "fairytale",
                "Fan Clock",
                "film projector",
                "film strip",
                "financial terminal device",
                "Finn and Jake",
                "first leak",
                "flat iron",
                "flatiron",
                "flexible time",
                "flooring",
                "fluid pump",
                "Fluorescent lamp",
                "fluorescent lamp holder",
                "Fluorescent lamp replacement LED lamp",
                "foot bath",
                "foot warmer",
                "for control circuit",
                "for device protection",
                "for double eyelids",
                "for electrical equipment",
                "for escalators",
                "for information retrieval",
                "For living radio station",
                "for playback",
                "For suppression of radio interference",
                "for the elderly",
                "for youth",
                "Fornasetti",
                "FRAISE",
                "Freddy",
                "frequency",
                "frying pan",
                "fur",
                "fuse",
                "GANZZI",
                "gas",
                "gas lighter",
                "general use bicycle",
                "geographical",
                "geometry",
                "germanium",
                "gigabyte",
                "glow starter",
                "goose",
                "governor",
                "Gravity Quilt",
                "green laser",
                "grinder",
                "ground connection",
                "guitar lamp holder",
                "gun",
                "gym",
                "Half/Full body bath",
                "halogen bulb",
                "halogen luminaire",
                "Harajuku",
                "hard hat",
                "heat pack",
                "heater",
                "hello kitty",
                "helmet",
                "hemp",
                "hero",
                "hewolf naturehike aegismax",
                "high voltage discharge luminaire",
                "hip",
                "hippo",
                "holder",
                "home automation",
                "home pressure pot",
                "hot water mat",
                "Howl",
                "Hulk",
                "hydraulic",
                "hydrogen generator",
                "Ice cream",
                "Idol",
                "Idols",
                "IFACE",
                "Imbly",
                "imvely",
                "incandescent lamp",
                "incandescent light bulb",
                "individual user",
                "infrared ray",
                "injection",
                "insulated wire",
                "interconnect coupler",
                "internet multimedia",
                "Ireland",
                "Ironing",
                "island",
                "isolating transformer",
                "J.ESTINA",
                "Jacquemus",
                "Jake",
                "Jay-Z",
                "Jerry",
                "Johnson's Baby",
                "joker",
                "Joyful Shine",
                "kakao",
                "Kaonashi",
                "Karina",
                "Kawaii",
                "Kenzo",
                "kids",
                "Kitty",
                "knee",
                "knot",
                "knot cushion",
                "korea",
                "Korean Wave",
                "kpop",
                "k-pop",
                "lace ring",
                "lacoste",
                "ladder",
                "lamp holder",
                "language practice",
                "laptop computer",
                "laser",
                "laser equipment",
                "learner",
                "led",
                "led clock fan",
                "LED 전원공급장치",
                "LED등기구",
                "LED램프",
                "leg",
                "Lens Cleaning",
                "lesbian",
                "life jacket",
                "light bulb shape",
                "lighting equipment",
                "lighting fixtures",
                "Limited Offer",
                "Lindbergh",
                "lint remover",
                "lithium",
                "lobster",
                "lock",
                "LOL",
                "louis vuitton",
                "LOVEMEI",
                "Lowepro",
                "Luffy",
                "Luxilon",
                "luxlon",
                "luxury brand",
                "macaroon",
                "machine",
                "magnetic ballast",
                "Magnetic ballast for lamps",
                "manga",
                "manganese",
                "Marble",
                "marble deer",
                "Marc",
                "Marc Jacobs",
                "Marcelo Burlon",
                "mark ryden",
                "Marvel",
                "massager",
                "MCM",
                "Medical treatment",
                "medicinal herbs",
                "MEIZU",
                "Memories drop by drop",
                "menstruation",
                "message fan",
                "message fanusb",
                "metal ring",
                "Mickey Mouse",
                "milk drink",
                "milking machine",
                "mini transformer",
                "mink",
                "modulator",
                "molding machine",
                "MONDRIAN",
                "monkey",
                "monster",
                "moomin",
                "moose",
                "motomo",
                "motorized board",
                "mountain bike",
                "Mouthpiece",
                "mower",
                "Mr. Touch",
                "msgm",
                "Mulberry",
                "muumin",
                "muzi",
                "naked",
                "naked woman",
                "nausicaa of the valley of the wind",
                "navigation",
                "nearsighted",
                "needle",
                "Neo Hybrid",
                "neon transformer",
                "North Korea",
                "number ticket",
                "nursing pad",
                "OBLIQ",
                "OHP",
                "oil",
                "oil stove",
                "Omron",
                "one piece",
                "Other wireless devices for location-based services",
                "overload protection",
                "padieoe",
                "padio",
                "Pancoat",
                "panda",
                "Pandora",
                "panerai",
                "Payphone",
                "peaceminusone",
                "pellet",
                "Penguin",
                "pet bath",
                "Phantom mask",
                "philips",
                "Physiology",
                "Pikachu",
                "pineapple",
                "pinhole",
                "Pink Panther",
                "Pistol Type Arc Adhesive",
                "Pixar",
                "planter",
                "platform",
                "platform door lock",
                "player",
                "PLS",
                "PLS방식 무전극램프",
                "PLS조명기구",
                "plug",
                "plug and outlet",
                "pocketemon",
                "podium",
                "Pokemon",
                "polo ralph",
                "polyvinyl chloride tube",
                "pooh",
                "portable jack",
                "potato peeler",
                "power cord",
                "power distributor",
                "power filter",
                "Power filter for suppression of radio interference",
                "Power socket",
                "power supply",
                "Power Supply for Computers",
                "power tools",
                "pregnancy",
                "Pregnant",
                "Press",
                "pressure cooker",
                "pressure pot",
                "projector",
                "protective gear",
                "rabbit ears",
                "raccoon",
                "Raccoons",
                "radio",
                "Radios",
                "real imager",
                "rebound",
                "receiver",
                "receiving set",
                "rechargeable battery",
                "recycled tire",
                "red pig",
                "regenerative",
                "regenerative tires for automobiles",
                "remote control broadcasting device",
                "remote control switch",
                "repair parts",
                "replacement parts",
                "reverse run",
                "Reverse running prevention device for escalator",
                "Rilakkuma",
                "RIPNDIP",
                "rockbros",
                "roller skating",
                "roller sports",
                "rowing machine",
                "running shoes on wheels",
                "rupee",
                "rupture valve",
                "Ryan",
                "Ryden",
                "safety circuit board",
                "Sailor",
                "Sailor Moon",
                "samsung",
                "sandisk",
                "satellite broadcast receiver",
                "scanner",
                "seed",
                "SellDone",
                "Sennheiser",
                "Senwachihiro",
                "set top box",
                "sex",
                "sexual intercourse",
                "sexy girl",
                "sgp",
                "Shake Lobster",
                "Sheldon",
                "Shimano",
                "shopping cart",
                "short circuit",
                "signal processor",
                "SK Telecom",
                "skateboard",
                "ski",
                "ski binding",
                "ski boots",
                "ski equipment",
                "skin care device",
                "SKT1",
                "slide",
                "slip",
                "smart clear",
                "smiley",
                "smurf",
                "snowboard",
                "Soft Vinyl Chloride Hose",
                "Song Hye-kyo",
                "Song Joong-Gi",
                "Sonny Angel",
                "sound quality adjuster",
                "spg",
                "spider",
                "Spiderman",
                "spigen",
                "Sponge Bob",
                "Spongebob",
                "starbucks",
                "starter",
                "Starter holder for fluorescent lamps",
                "stationary bike",
                "stationary exercise equipment",
                "steam cooker",
                "step",
                "step chain",
                "stepper",
                "stereoscopic imager",
                "Steve Rogers",
                "stitch",
                "stone island",
                "stop device",
                "stroller",
                "student",
                "subscriber terminal device",
                "Superman",
                "switch",
                "switch for control circuit",
                "switch for electrical equipment",
                "Tai Chi",
                "teen bb gun",
                "Teenager",
                "Temperature overheat prevention device",
                "terminal device",
                "thermal fuse",
                "thermometer",
                "thermostat",
                "THRASHER",
                "ticket machine",
                "tile",
                "time delay switch",
                "Timer and time switch",
                "tire",
                "titlelist",
                "tori",
                "totoro",
                "touch-c",
                "towel wrapping machine",
                "Transformers",
                "transportation card charger",
                "tread rubber",
                "Tread rubber for tire regeneration",
                "treadmill",
                "trigger",
                "trimming machine",
                "truck",
                "tuner",
                "turn-by-turn",
                "turntable",
                "two-wheeled bicycle",
                "U style holder",
                "Ugly Bros",
                "Ugly Brothers",
                "uglybros",
                "ultra scene",
                "ultra thin",
                "ultrasonic cleaner",
                "ultrasonic wave",
                "ultraviolet ray",
                "valfre",
                "Van Cleef",
                "ventilation",
                "verus",
                "Vetem ents",
                "Vetements",
                "video camera",
                "video distributor",
                "video door phone",
                "video phone",
                "video receiver",
                "video recorder",
                "video transmitter",
                "virtual reality",
                "Vision",
                "voice player",
                "vulva",
                "washer",
                "waste heat",
                "waste heat recovery",
                "Waste heat recovery ventilator",
                "water fountain",
                "water freeze protector",
                "water rides",
                "water tank",
                "wet towel machine",
                "whirlpool bathtub",
                "whole body",
                "wiggle",
                "Wiggle Wiggle",
                "Wipes",
                "Witch's Delivery Service Kiki",
                "Wonder Woman",
                "XㆍY 커패시터",
                "yamamoto",
                "yeezy",
                "Yeti",
                "yohji",
                "zeiss",
                "Zenus",
                "가상 현실",
                "가스",
                "가스라이터",
                "가오나시",
                "가입자단말 장치",
                "가재",
                "가정용 압력냄비",
                "감자탈피기",
                "개인 사용자",
                "거위",
                "거치대",
                "건전지",
                "게르마늄",
                "겐조",
                "고령자용",
                "고압방전등기구",
                "고정식운동기구",
                "고정식자전거",
                "공중전화",
                "과부하보호",
                "관장",
                "교체 부품",
                "교통카드 충전기",
                "구명복",
                "구스",
                "권총형아크접착기",
                "귀 패드",
                "근시",
                "글로우스타터",
                "금속링",
                "금융단말기기",
                "금전등록기",
                "기가바이트",
                "기계",
                "기기보호용",
                "기기보호용 차단기",
                "기름난로",
                "기타 램프 홀더",
                "기타 위치기반 서비스용 무선기기",
                "기포발생기",
                "기하학",
                "까마귀",
                "난시",
                "남근",
                "내비게이션",
                "내장형램프",
                "너구리",
                "네오 하이브리드",
                "네온변압기",
                "노트북컴퓨터",
                "녹색 레이저",
                "누전",
                "누전차단기",
                "눈보호구",
                "늑대",
                "다림질",
                "닥터",
                "단락겸용",
                "단말기기",
                "대나무 밴드",
                "대리석 사슴",
                "대마",
                "도넛",
                "도라에몽",
                "도수",
                "도어록",
                "동전계수기",
                "두카티",
                "드라코",
                "드래곤 볼",
                "등산용로프",
                "디스크",
                "디자인 만화",
                "디즈니",
                "디지털도어록",
                "라디오",
                "라이언",
                "라코스테",
                "랍스타",
                "랍스터",
                "램프용 자기식안정기",
                "램프용 전자식안정기",
                "램프홀더",
                "러닝머신",
                "럭슬론",
                "럽쳐밸브",
                "레그",
                "레이스 링",
                "레이저",
                "레이저용품",
                "레즈비언",
                "로잉 머신",
                "롤러스케이트",
                "롤러스포츠",
                "루이비통",
                "루피",
                "리락쿠마",
                "리모트콘트롤스위치",
                "리바운드",
                "리시버",
                "리튬",
                "린드버그",
                "마녀배달부 키키",
                "마블",
                "마사지기",
                "마약",
                "마우스피스",
                "마카롱",
                "마크 ryden",
                "마크제이콥스",
                "만화",
                "망간",
                "卖家",
                "매듭",
                "매듭 쿠션",
                "맥주 케이스",
                "메세지 선풍기",
                "메시지 팬",
                "명품 브랜드",
                "모듈레이터",
                "모터 달린 보드",
                "모토모",
                "모피",
                "몬드리안",
                "몬스터",
                "몽키",
                "무릎",
                "무민",
                "무선 헤드셋",
                "무선마이크",
                "무선스피커",
                "무전극램프",
                "무전기",
                "물놀이기구",
                "물수건마는기기",
                "물수건포장기",
                "물탱크",
                "미끄럼",
                "미운 브라더스",
                "미키 마우스",
                "밍크",
                "바늘",
                "바닥재",
                "바람의 계곡 나우시카",
                "바바파파",
                "바인딩",
                "바퀴 달린 운동화",
                "반신·전신욕조",
                "반클리프",
                "발 보온기",
                "발보온기",
                "발욕조",
                "발행기",
                "방전램프",
                "방탄 소년단",
                "방탄소년단",
                "배경막",
                "배선용차단기",
                "배터리",
                "배트맨",
                "백열등기구",
                "백열전구",
                "버스정류장 버스 안내 시스템",
                "버터플라이",
                "번호표",
                "벌거 벗은",
                "범퍼 링",
                "범퍼 쿠션",
                "벗은 여자",
                "베루스",
                "벤치 프레스",
                "변압기",
                "보디 빌딩",
                "보양",
                "보우트",
                "보이 런던",
                "보일러",
                "보조 베터리",
                "보조복",
                "보조용품",
                "보풀제거기",
                "보행보조차",
                "보호장구",
                "복합단말기기",
                "본챔스",
                "부력",
                "부스터",
                "부츠",
                "부탄",
                "북한",
                "분쇄기",
                "불량 토끼",
                "붉은돼지",
                "브레이크",
                "브레이크액",
                "블라인드",
                "비디오도어폰",
                "비디오카메라",
                "비디오폰",
                "비비탄",
                "비비탄 총",
                "비상 정지장치",
                "비웰",
                "비투비",
                "빅뱅",
                "사다리",
                "사슴",
                "사슴 대리석",
                "사용자",
                "산악용자전거",
                "상승과속 방지장치용 브레이크",
                "상호연결커플러",
                "생리",
                "생활무선국용",
                "석유",
                "성교",
                "성인용",
                "성인용 비비탄 총",
                "성형기",
                "세일러",
                "세일러 문",
                "세정기",
                "섹시한 여자",
                "센과치히로",
                "셀던",
                "셋톱박스",
                "소니엔젤",
                "소용돌이욕조",
                "소형변압기",
                "속눈썹",
                "송중기",
                "송혜교",
                "쇼핑카트",
                "수도 동결 방지기",
                "수리 부품",
                "수소 발생기",
                "수신기",
                "수영",
                "수유패드",
                "순번대기기",
                "쉐이크 랍스터",
                "슈퍼맨",
                "슈피겐",
                "스노보드",
                "스마일리",
                "스마트 클리어",
                "스위치",
                "스캐너",
                "스케이트보드",
                "스키",
                "스키바인딩",
                "스키용구",
                "스키화",
                "스타벅스",
                "스타터",
                "스텝",
                "스텝체인",
                "스텝퍼",
                "스토브",
                "스톤 아일랜드",
                "스톤아일랜드",
                "스티브 로저스",
                "스티치",
                "스파이더",
                "스파이더맨",
                "스폰지 밥",
                "슬라이드",
                "승강장",
                "승강장 문 잠금장치",
                "승차용",
                "시간지연스위치",
                "시력",
                "시마노",
                "신호처리기",
                "실물화상기",
                "쌍꺼풀용",
                "씨앗",
                "아기",
                "아이돌",
                "아이스크림",
                "아일랜드",
                "안전모",
                "안전회로기판",
                "안정기",
                "안정기내장형 LED램프",
                "알몸",
                "알칼리",
                "알파인용",
                "암 밴드",
                "암밴드",
                "압력냄비",
                "압력솥",
                "애니메이션",
                "애완동물 목욕기",
                "앰프",
                "야수",
                "약초",
                "어글리 브로스",
                "어글리브로스",
                "어린이",
                "어피치",
                "어학실습기",
                "엉덩이",
                "에너지 레귤레이터",
                "에너지 저장장치",
                "에디슨",
                "에디슨 나사형 홀더",
                "에스컬레이터용",
                "에스컬레이터용 역주행 방지장치",
                "엘사",
                "엘크",
                "역주행",
                "연결부품",
                "연소",
                "연질염화비닐호스",
                "영상기록계",
                "영상분배기",
                "영상수신기",
                "영상전송기",
                "预定",
                "예초기",
                "예티",
                "오리",
                "오므론",
                "온도계",
                "온도과승방지장치",
                "온도조절기",
                "온도퓨즈",
                "온수매트",
                "온열팩",
                "완충기",
                "왕관",
                "왕관 펜던트 목걸이",
                "외음부",
                "우유 음료",
                "운동용슬라이더",
                "울트라 씬",
                "울트라신",
                "울트라씬",
                "원격제어방송기기",
                "원더 우먼",
                "원피스",
                "위글",
                "위성방송수신기",
                "유모차",
                "유방",
                "유아",
                "유압식",
                "유연한 시간",
                "유체펌프",
                "음성기록계",
                "음성플레이어",
                "음주",
                "음질조절기",
                "의료",
                "이륜자전거",
                "이어 패드",
                "인터넷멀티미디어",
                "일반용자전거",
                "임블리",
                "임신",
                "입체영상기",
                "자기식안정기",
                "자동압력 스위치",
                "자동차 디자인",
                "자동차용 재생타이어",
                "咨询",
                "자외선",
                "자이스",
                "잠금장치",
                "재단기",
                "재배기",
                "재생용",
                "재생타이어",
                "적외선",
                "전구모양",
                "전기 빵 자르개",
                "전기구동 모터 기동릴레이",
                "전기기기",
                "전기기기용 스위치",
                "전기기기용접속기류",
                "전기난방기",
                "전기냉장·냉동기기",
                "전기방석",
                "전기분수기",
                "전기설비용",
                "전기설비용 스위치",
                "전기세척기",
                "전기소자기",
                "전기스탠드",
                "전기시계",
                "전기온수매트",
                "전기온수침대",
                "전기온수펌프",
                "전기욕조",
                "전기용접기",
                "전기이온수기",
                "전기자전거",
                "전기정미기",
                "전기정수기",
                "전기주류 숙성기",
                "전기찜질기",
                "전기찜질기,",
                "전기충전기",
                "전기침대",
                "전기헬스기구",
                "전동공구",
                "전동보드",
                "전동타자기",
                "전선",
                "전신",
                "전열보드",
                "전원공급장치",
                "전원분배기",
                "전원코드",
                "전원필터",
                "전자개폐기",
                "전자보드",
                "전자브레이크",
                "전자시계",
                "전자식 스위치",
                "전자식스타터",
                "전자칠판",
                "전자테이블",
                "전지",
                "전파장해억제용",
                "전파장해억제용 전원필터",
                "전화기",
                "절단 기계",
                "절연변압기",
                "절연전선",
                "접지",
                "정력",
                "정보검색용",
                "정수기",
                "定制",
                "정지장치",
                "제누수",
                "제리",
                "제모기",
                "제어회로용",
                "제어회로용 스위치",
                "제이지",
                "젠하이저",
                "조광기",
                "조명기구",
                "조명기구용컨버터",
                "조명기기",
                "조속기",
                "조속기(調速機)",
                "조커",
                "주사",
                "중력 이불",
                "증기조리기",
                "증류",
                "지리적",
                "지폐계수기",
                "직류전원장치",
                "차단기",
                "착유기",
                "청소년",
                "청소년용",
                "청소년용 비비탄 총",
                "체온계",
                "체육관",
                "체인형",
                "초등학생",
                "초음파",
                "초음파세척기",
                "총",
                "쵸파",
                "추억은 방울방울",
                "축열식",
                "충전기",
                "충전용 전동공구",
                "충전지",
                "치히로",
                "카리나",
                "카멜백",
                "카카오",
                "캐시미어",
                "캡틴",
                "커패시터",
                "컴퓨터용 전원공급장치",
                "컴프레서",
                "컴프레서 게이트",
                "케이팝",
                "코듀로이",
                "코드",
                "코드세트",
                "코드스위치",
                "콘센트",
                "콜드",
                "크라운",
                "큰가슴",
                "클리너",
                "클리어 뷰",
                "키즈",
                "키티",
                "타이머 및 타임스위치",
                "타이어",
                "타이어 재생용 트레드고무",
                "타이치",
                "타일",
                "탈수기",
                "태양의 후예",
                "터치씨",
                "턴테이블",
                "토끼 귀",
                "토리",
                "토토로",
                "투영기",
                "튜너",
                "트럭",
                "트레드고무",
                "트리거",
                "트리밍기",
                "티켓 발행기",
                "파디오",
                "파인애플",
                "판더",
                "판도라",
                "팬더",
                "팬텀 마스크",
                "페어리 테일",
                "페이퍼랑",
                "펠릿",
                "펭귄",
                "편집기",
                "폐열",
                "폐열 회수",
                "폐열 회수 환기장치",
                "포디엄",
                "포켓몬",
                "폴로 랄프",
                "폴리염화비닐관",
                "푸우",
                "퓨즈",
                "프라이 팬",
                "프레스",
                "플랫 아이언",
                "플랫아이언",
                "플러그",
                "플러그 및 콘센트",
                "플레이어",
                "피부관리기",
                "피카츄",
                "픽사",
                "핀과제이크",
                "핀홀",
                "필름스트립",
                "필름투영기",
                "필립스",
                "하라주쿠",
                "하마",
                "하울",
                "학생",
                "학습기",
                "한국",
                "한류",
                "할로겐등기구",
                "할로겐전구",
                "항문",
                "헐크",
                "헬로 키티",
                "현금자동취급기",
                "형광등",
                "형광등기구",
                "형광등용 스타터 홀더",
                "형광등용 커패시터",
                "형광램프 대체형 LED램프",
                "형광램프 홀더",
                "홀더",
                "홈오토메이션",
                "환기장치",
                "휘트니스",
                "휴대용잭",
                "휴대전화 배터리 충전기",
                "히어로",
                "히터",
                "accessories"));

        return arrayList;

    }

    public static ArrayList<String> getExcWordList(){
        ArrayList<String> arrayList = new ArrayList<>(Arrays.asList("전면 폐쇄",
                "및 지원",
                "2023",
                "2019",
                "2018",
                "2017",
                "2016",
                "2015",
                "저렴한",
                "이음매없는",
                "한국어 스타일",
                "한국어스타일",
                "2021 년",
                "2021년",
                "2022 년",
                "2022년",
                "new ",
                "22ss ",
                "친환경",
                "뜨개질",
                "새로운 도착",
                "국경 핫",
                "핫 세일",
                "한국 충돌",
                "CMAZ",
                "프리 사이즈",
                "무료 사이즈",
                "조수 ",
                "경적 ",
                "대조적인",
                "대조적 인",
                "DEAT ",
                "박쥐",
                "사전 판매",
                "사전판매",
                "동일한 ",
                "야자",
                "코코넛",
                "엄선 된",
                "무두질 된",
                "무두질",
                "슈퍼 품질",
                "무료 배송",
                "채찍으로 치다",
                "매우",
                "리얼 샷",
                "새헤에",
                "게으른",
                "따뜻한",
                "정품",
                "유명",
                "쉬운",
                "쉬움",
                "착용하기",
                "개인화",
                "신제품",
                "통기성",
                "브랜드",
                "진짜",
                "가격",
                "모유",
                "깔개",
                "간단한",
                "한국",
                "촬열을위한",
                "뻗치다",
                "여성을이한",
                "크로셰",
                "뜨개실",
                "중공",
                "우아한",
                "LET'S SLIM",
                "spigen",
                "슈피겐",
                "비키니아일랜드",
                "bikiniisland",
                "visca",
                "VISKA",
                "비스카",
                "lamatree",
                "라마트리",
                "printec",
                "프린텍",
                "도깨비방망이",
                "homniz",
                "홈니즈",
                "wonderbooster",
                "hoobooster",
                "후부스터",
                "E-Land",
                "이랜드",
                "MISUMI",
                "HANSHIN",
                "HANSHINTOOLS",
                "EvaArmisen",
                "에바알머슨",
                "에스엘바이오텍",
                "Slbiotech",
                "nutricore",
                "sothing",
                "artworks",
                "아트웍스코리아",
                "펫긱",
                "PETGEEK",
                "ABUBA",
                "제이에스티나",
                "꼭고핀",
                "꼭꼬핀",
                "꼬꼬핀",
                "DUPONT",
                "듀퐁",
                "바오바오 ",
                "ZEROONE",
                "baobao ",
                "효도의자",
                "트레킹",
                "현빈",
                "싱가포르",
                "배달",
                "쿠폰",
                "할인",
                "까마귀",
                "높은",
                "한국어",
                "당겨",
                "세일",
                "시뮬레이션",
                "벽돌",
                "속보",
                "나쁜",
                "판매",
                "를위한",
                "있음",
                "재고",
                "미친",
                "B-STYLE",
                "FREEing",
                "자폐증",
                "#",
                "간단하게",
                "보양",
                "!!!",
                "!!",
                "!",
                "핫세일",
                "도매",
                "로우컷",
                "배송",
                "무료배송",
                "무료",
                "느슨한",
                "비정형",
                "숙녀",
                "새로운",
                "원활한",
                "매달려",
                "이음새가없는",
                "교수형",
                "주최자",
                "을위한",
                "탄력있는",
                "중국",
                "휴일",
                "폴카 ",
                "타이 ",
                "분할 ",
                "고품질",
                "고삐",
                "치다",
                "사진",
                "기하학",
                "촬영을위한",
                "중공업",
                "일치",
                "모든",
                "여자에",
                "고귀한",
                "회화",
                "중국어",
                "수요에",
                "뜨거운",
                "저녘 ",
                "부드러운",
                "편안하고",
                "컨디션",
                "씻어",
                "유형",
                "2022",
                "2021",
                "2020",
                "DUNHILL",
                "Benjamin Moore",
                "간섭 ",
                "감옥학원",
                "던힐",
                "방해 ",
                "불사조 "));
        return arrayList;
    }
}
