mybatis:
  mapper-locations: classpath*:META-INF/persistence/mybatis/mapper/**/*.xml
  type-aliases-package: com.plexter.sellter.agent.**.vo

spring:
  datasource:
#    url: jdbc:sqlite:C:/Workspace/sellter/sellter.agent.spring/sellter.sqlite3
    url: jdbc:sqlite:C:/Workspace/sellter/sellter.agent.spring/sellter_sean.sqlite3
    driver-class-name: org.sqlite.JDBC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  artemis:
    mode: native
    broker-url: "tcp://tsdavid9.ddns.net:7222"
    user: "admin"
    password: "admin"

scrap:
  resource:
    path: C:/Workspace/sellter/sellter.agent.ali.scarpper/scrapService.js

ems:
   #host: "tcp://tsdavid9.ddns.net"
   host: "tcp://localhost"
   port: "7222"
   user: "admin"
   password: ""
   destination:
     receive: "slt.receive.queue"
     request: "slt.request.queue"