server:
  port: 8088

mybatis:
  mapper-locations: classpath*:META-INF/persistence/mybatis/mapper/**/*.xml
  type-aliases-package: com.plexter.sellter.agent.**.vo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null

spring:
  jpa:
    database-platform: com.tsh.slt.agent.SqlDialect
    hibernate:
      ddl-auto: update
  datasource:
#    url: jdbc:sqlite:C:/Workspace/sellter/sellter.agent.spring/sellter_sean.sqlite3
    url: jdbc:sqlite:sqlitesample-agent.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true