mybatis:
  mapper-locations: classpath*:META-INF/persistence/mybatis/mapper/**/*.xml
  type-aliases-package: com.plexter.sellter.agent.**.vo

spring:
  datasource:
    url: jdbc:sqlite:C:/Workspace/sellter/sellter.agent.spring/sellter.sqlite3
    driver-class-name: org.sqlite.JDBC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher